var myString;
var myNum;
var myBool;
var myVar;
var numArr;
var strArr;
var strNumTuple;
myString = 'aloha';
myNum = 77;
myBool = false;
// console.log(myString);
// console.log(myNum);
// console.log(myBool);
// console.log(myVar);
strArr = ['hello', 'world'];
console.log(strArr);
strNumTuple = ['helloe', 1];
console.log(strNumTuple);
